### ISSUE TITLE
Viac vysledkov pre jedno ICO

### ISSUE THREAD

**Issue by ondrejvlcek** [lubosdz/parser-orsr#10]
Moze nastat situacia ze pre jedno ICO je viac vysledkov

https://www.orsr.sk/hladaj_ico.asp?ICO=45281025

SRO medzitym zmenila nazov aj adresu. Parser spracuje udaje z prveho vysledku, ale spravny je (predpokladam ze vzdy) prave ten druhy. V nespravnom vysledku je takato informacia

**Spis odstúpený na iný registrový súd z dôvodu miestnej nepríslušnosti**

**Comment by lubosdz** [comment]
Nie je to vzdy tak, bohuzial treba preverit kazdy stiahnuty subjekt a vratit prvy, ktory neobsahuje uvedeny retazec "Spis odstúpený ...". Bude opravene v najblizsom release. Dakujem.

**Comment by lubosdz** [comment]
Solved in release 1.1.0 on 13.11.2023.
