### ISSUE TITLE
Nie je mozne nacitat DOM orsr kvoli nespravnemu kodovaniu

### ISSUE THREAD

**Issue by MarekGogol** [lubosdz/parser-orsr#4]
**riadok 531**
```
$xml = new \DOMDocument('1.0', 'utf-8');
$xml->loadHTML($html);

$xpath = new \DOMXpath($xml);
```

![image](https://user-images.githubusercontent.com/11134410/57643313-bbb34b80-75b9-11e9-98a3-4d11937e7825.png)

V tejto casti nastane chyba, kedze sa php pokusa nacitat string, ktory je kodovany nespravne. Tato chyba nastava o riadok vyssie, kedy preg_replace pokazi kodovanie stringu. Deje sa to len na niektorych PHP verziach, ktore boli skompilovane inym sposobom. Spravne v tychto pripadoch treba pouzit flag **u**.
```
$html = preg_replace('/\s+/', ' ', $html);
$html = preg_replace('/\s+/u', ' ', $html);
```

Vytvoril som uz pull request, prosim o aplikovanie. #3 

https://maxivak.com/working-with-regular-expressions-preg_-and-utf-8-strings-in-php/
https://stackoverflow.com/questions/35887031/why-does-w-match-non-english-characters-in-mac-os-x-php-environment

**Comment by MarekGogol** [comment]
Dakujem za merge. Prosim o vytvorenie tagu.

**Comment by lubosdz** [comment]
Released 1.0.2, composer updated.
Thank you.

Just a small aside note 
It would be useful to let know how to simulate error. 
E.g. `$orsr->getDetailById(11370, 6);` will crash with DOM entity error + what environment (Mac?), PHP version.
Currently I tested my previous working samples, they work with your patch, but I am not able to emulate error you experienced.

**Comment by MarekGogol** [comment]
@lubosdz Thanks.

Sorry for missing info.

# Environment

PHP: **7.1.x/7.2.17 (must be downloaded from Homebrew)** (with default PHP in mac OS package works properly.)
OS: **Mac OS**

# Code

```
$orsr = new \lubosdz\parserOrsr\ConnectorOrsr();

$data = $orsr->getDetailById(5994, 2);
```

# Error
![image](https://user-images.githubusercontent.com/11134410/57690215-70dd1680-7641-11e9-96c5-4f3e62a74c05.png)

**Comment by lubosdz** [comment]
@MarekGogol Thanks, will check it.
