### ISSUE TITLE
getDetailByICO nevracia detail ale list

### ISSUE THREAD

**Issue by Sorien** [lubosdz/parser-orsr#5]
ak to dobre chapem `getDetailByICO` by ma vratit detail rovnako ako `getDetailByPartialLink` ale vracia list s 1 polozkou ako `findByObchodneMeno`

**Comment by lubosdz** [comment]
Ano, vdaka za upozornenie. Parser bol vytiahnuty z ineho projektu, bolo by ho treba konzistentne prepisat ... Bola pridana metoda `findByIco`, ktora robi to, co predtym `getDetailByIco` a getDetailByICO vracia detail subjektu. 

Je to BC break, v pripade potreby staci len premenovat `getDetailByICO` -> `findByICO`.

https://github.com/lubosdz/parser-orsr/blob/master/ConnectorOrsr.php#L349
