### ISSUE TITLE
Pouzitie bez "tidy"

### ISSUE THREAD

**Issue by richardbdzoch** [lubosdz/parser-orsr#6]
Zdravim. V prvom rade pekne dakujem, velmi uzitocna klasa 👍 . Len by som pre zaujimavost spomenul moj pripad pouzitia:
Na serveri nemam k dispozicii tidy php extension a instalacia stoji namahu viacero ludi :D
Tak som dal (namiesto efektu tidy-cka) sancu kombinacii :
`
libxml_use_internal_errors(true);
...
$xml = new \DOMDocument('1.0', 'utf-8');
$xml->preserveWhiteSpace = false;
`

Samozrejme, tidy-ckove casti kodu som zakomentoval. Riadok `libxml_use_internal_errors(true);` sluzi na to, aby volanie `$xml->loadHTML($html);` nepadlo do chyby na nevalidnom html. Riadkom `$xml->preserveWhiteSpace = false;`  hovorim DOMDocument-u, aby ignoroval whitespace-y medzi tagmi (inak by ich bral ako sucast dom). 

Vysledok vyzera pouzitelne. Pouzivam vsak len metodu `getDetailByICO()`, takze neviem, mozno to neriesi globalne vsetky funkcie klasy...

**Comment by lubosdz** [comment]
Ahoj, 
bez `tidy` sa vyznamne zvysuje riziko chyby pri nacitani XHTML do DomDocument. ORSR.sk bezi na starom IIS ASP, ktoreho sa roky nikto nedotkol, vkladaju tam rucne stringy v nepredvidatelnom formate a nie je preto mozne garantovat, ze kod bude korektne fungovat. 

Napriek tomu, poznam pripady, kedy hostingy nedokazu upravit PHP prostredie - najma pre starsie verzie PHP.
Z toho dovodu bola teda pridana moznost vypnut opravu XML stringu nastavenim `$orsr->useTidy = false`.
Released in `1.0.6`.
