### ISSUE TITLE
PHP 8.1 Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by hanisko** [lubosdz/parser-orsr#8]
Deprecated trim with null value may be possible issue in future.

https://stackoverflow.com/questions/71707325/migration-to-php-8-1-how-to-fix-deprecated-passing-null-to-parameter-error-r

**Comment by lubosdz** [comment]
Cannot find any error / warnings when executing test on PHP 8.1. Please dump stacktrace here or specify line with the issue. Thank you.

**Comment by lubosdz** [comment]
Closing, tests passing 8.2.3.
